name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  testOutputPath: 
    description: 'Test Output Path'
    required: true
    default: 'invalid'
  slackChannelId:
    description: 'Slack Conversation ID ie: C12355667'
    required: true
    default: 'invalid'
  slackToken:
    description: 'Secret Slack Token'
    required: true
    default: 'invalid'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'